apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    name: alpine
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234

---

apiVersion: v1
kind: Pod
metadata:
  name: alpine01
  namespace: default
  labels:
    name: alpine
spec:
  hostname: alpine01
  subdomain: default-subdomain
  containers:
  - image: alpine:latest
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always

---

apiVersion: v1
kind: Pod
metadata:
  name: alpine02
  namespace: default
  labels:
    name: alpine
spec:
  hostname: alpine02
  subdomain: default-subdomain
  containers:
  - image: alpine:latest
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    imagePullPolicy: IfNotPresent
    name: alpine
  restartPolicy: Always

  